import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../../dashboard/domain/models/expense.dart';
import '../../analytics/presentation/providers/analytics_provider.dart';

class PdfExportService {
  static Future<void> generateAndShareFinancialReport({
    required String userName,
    required List<Expense> recentExpenses,
    required AnalyticsData analytics,
  }) async {
    final pdf = pw.Document();

    final font = await PdfGoogleFonts.plusJakartaSansRegular();
    final fontBold = await PdfGoogleFonts.plusJakartaSansBold();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('MESS BUDDY', style: pw.TextStyle(font: fontBold, fontSize: 24, color: PdfColors.deepPurple)),
                      pw.Text('Official Financial Report', style: pw.TextStyle(font: font, fontSize: 14, color: PdfColors.grey700)),
                    ],
                  ),
                  pw.Text(DateFormat('dd MMM yyyy').format(DateTime.now()), style: pw.TextStyle(font: font, fontSize: 14)),
                ],
              ),
              pw.SizedBox(height: 30),

              // User Info
              pw.Text('Report Generated For: $userName', style: pw.TextStyle(font: fontBold, fontSize: 16)),
              pw.SizedBox(height: 20),

              // Summary
              pw.Container(
                padding: const pw.EdgeInsets.all(12),
                decoration: const pw.BoxDecoration(
                  color: PdfColors.grey100,
                  borderRadius: pw.BorderRadius.all(pw.Radius.circular(8)),
                ),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                  children: [
                    _buildSummaryItem('Total Spent', '₹${analytics.monthlySpending.toStringAsFixed(0)}', font, fontBold),
                    _buildSummaryItem('Burn Rate', '₹${analytics.burnRate.toStringAsFixed(0)}/day', font, fontBold),
                    _buildSummaryItem('Transactions', '${recentExpenses.length}', font, fontBold),
                  ],
                ),
              ),
              pw.SizedBox(height: 30),

              // Breakdown
              pw.Text('Category Breakdown', style: pw.TextStyle(font: fontBold, fontSize: 16)),
              pw.Divider(),
              pw.SizedBox(height: 10),
              ...analytics.categoryBreakdown.entries.map((e) {
                return pw.Padding(
                  padding: const pw.EdgeInsets.symmetric(vertical: 4),
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text(e.key.toUpperCase(), style: pw.TextStyle(font: font, fontSize: 12)),
                      pw.Text('₹${e.value.toStringAsFixed(0)}', style: pw.TextStyle(font: fontBold, fontSize: 12)),
                    ],
                  ),
                );
              }),

              pw.SizedBox(height: 30),

              // Recent Transactions Table
              pw.Text('Recent Transactions Snapshot', style: pw.TextStyle(font: fontBold, fontSize: 16)),
              pw.SizedBox(height: 10),
              pw.TableHelper.fromTextArray(
                headerStyle: pw.TextStyle(font: fontBold, color: PdfColors.white),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.deepPurple),
                cellStyle: pw.TextStyle(font: font),
                cellAlignment: pw.Alignment.centerLeft,
                headers: ['Date', 'Title', 'Category', 'Amount'],
                data: recentExpenses.take(15).map((e) {
                  return [
                    DateFormat('dd MMM').format(e.date),
                    e.title,
                    e.category,
                    '₹${e.amount.toStringAsFixed(0)}'
                  ];
                }).toList(),
              ),

              pw.Spacer(),
              
              // Footer
              pw.Center(
                child: pw.Text(
                  'Auto-generated by Mess Buddy • Offline Tracking Engine',
                  style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey500),
                ),
              ),
            ],
          );
        },
      ),
    );

    // Prompt user to save/share the generated byte stream natively
    await Printing.sharePdf(bytes: await pdf.save(), filename: 'MessBuddy_Report.pdf');
  }

  static pw.Widget _buildSummaryItem(String label, String value, pw.Font font, pw.Font fontBold) {
    return pw.Column(
      children: [
        pw.Text(label, style: pw.TextStyle(font: font, fontSize: 12, color: PdfColors.grey700)),
        pw.SizedBox(height: 4),
        pw.Text(value, style: pw.TextStyle(font: fontBold, fontSize: 18, color: PdfColors.black)),
      ],
    );
  }
}
